#
# Executes commands at login post-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Execute code that does not affect the current session in the background.
{
  # Compile the completion dump to increase startup speed.
  zcompdump="${ZDOTDIR:-$HOME}/.zcompdump"
  if [[ -s "$zcompdump" && (! -s "${zcompdump}.zwc" || "$zcompdump" -nt "${zcompdump}.zwc") ]]; then
    zcompile "$zcompdump"
  fi
} &!

# Execute code only if STDERR is bound to a TTY.
[[ -o INTERACTIVE && -t 2 ]] && {
  # Print a random, hopefully interesting, adage.
  if (( $+commands[fortune] )); then
    if [[ -t 0 || -t 1 ]]; then
      if (( $+commands[cowsay] )); then
        fortune 50% all 50% hackcave | cowsay -n
      else
        fortune 50% all 50% hackcave
      fi
      print
    fi
  fi
} >&2
