#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi
#export BROWSER='chromium'
export BROWSER='firefox'
#export BROWSER='vivaldi-stable'
#
# Editors
#
if (( $+commands[emacsclient] )); then
  export EDITOR='emacsclient -t -a vim'
  export VISUAL='emacsclient -c -a nvim'
elif (( $+commands[nvim] )); then
  export EDITOR='nvim'
  export VISUAL='nvim'
else
  export EDITOR='vim'
  export VISUAL='vim'
fi
export PAGER='less'
if (( $+commands[android-studio] )); then
  export ANDROID_HOME='/home/yash/Android/Sdk'
  export ANDROID_TOOLS='/home/yash/Android/Sdk/tools/'
  export ANDROID_PLATFORM_TOOLS='/home/yash/Android/Sdk/platform-tools/'
fi
#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

RUST_SRC_PATH=$(rustc --print sysroot)/lib/rustlib/src/rust/src

# Set the list of directories that Zsh searches for programs.
export GOPATH=/home/yash/git/go
path=(
  /usr/local/{bin,sbin,lib,games}
  /usr/{bin,games}
  /bin
  ~/bin
  .
  ./node_modules/.bin
  $GOPATH/bin
  ~/.local/bin
  ~/.cargo/bin
  $path
)
if (( $+commands[ruby] )); then
  path=(
    $(ruby -e "puts Gem.user_dir")/bin
    $path
  )
fi

if (( $+commands[android-studio] )); then
  path=(
    $ANDROID_HOME
    $ANDROID_TOOLS
    $ANDROID_PLATFORM_TOOLS
    $path
  )
fi
#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi
